import datetime
import os
import tomllib
from src.audiodevicedefinition import AudioDeviceDefinition
from src.pipewiredump import PipeWireDump


class Configuration:
    """
    Class for reading a conf.toml file

    c = Configuration('conf.toml')  # if the file exists it's loaded, otherwise a sample blank version is created
    c.get_default_audio_device()    # Always returns a AudioDeviceDefinition object, even if conf file is blank
    c.get_radio_audio_device()
    """
    def __init__(self, filename: str):
        self._filename = filename
        self._data = None

        if not os.path.exists(self._filename):
            self._create_default_configuration()

        with open(self._filename, "rb") as f:
            self._data = tomllib.load(f)

    def _get_audio_device(self, audio_type: str) -> AudioDeviceDefinition:
        # Start with a blank object, we always return a AudioDeviceDefinition
        device = AudioDeviceDefinition(
            sink          = "",
            source        = "",
            sink_volume   = -1.0,
            source_volume = -1.0
        )

        if self._data is not None and audio_type in self._data:
            device.sink          = self._data[audio_type].get("sink", "")
            device.source        = self._data[audio_type].get("source", "")
            device.sink_volume   = float(self._data[audio_type].get("sink_volume", -1.0))
            device.source_volume = float(self._data[audio_type].get("source_volume", -1.0))

        return device

    def get_default_audio_device(self) -> AudioDeviceDefinition:
        return self._get_audio_device("default_audio_device")

    def get_radio_audio_device(self) -> AudioDeviceDefinition:
        return self._get_audio_device("radio_audio_device")

    def _create_default_configuration(self):
        with open(self._filename, "w") as f:
            f.write("# autogenerated radio-interface-helper-ui config file @ {}\n".format(datetime.datetime.now()))
            f.write("#\n")
            f.write("# Found devices:\n")

            pwd = PipeWireDump()

            for node_name in pwd.get_all_node_names():
                node_id = pwd.get_node_id_by_name(node_name)
                f.write("# {}  ->  {}\n".format(node_id, node_name))

            f.write("\n")
            f.write("\n")

            f.write("[default_audio_device]\n")
            f.write("sink = \"\"\n")
            f.write("source = \"\"\n")
            f.write("sink_volume = -1.0  # -1.0 do not adjust audio when switching\n")
            f.write("source_volume = -1.0\n")
            f.write("\n")
            f.write("\n")

            f.write("[radio_audio_device]\n")
            f.write("sink = \"\"\n")
            f.write("source = \"\"\n")
            f.write("sink_volume = -1.0\n")
            f.write("source_volume = -1.0\n")
