import datetime
import os
import tomllib
from src.audiodevicedefinition import AudioDeviceDefinition
from src.pipewiredump import PipeWireDump


class Configuration:
    def __init__(self, filename: str):
        self._filename = filename
        self._data = None

        if not self.file_exists():
            self.create_default_configuration()

        self.load()

    def file_exists(self) -> bool:
        return os.path.exists(self._filename)

    def load(self):
        with open(self._filename, "rb") as f:
            self._data = tomllib.load(f)

    @staticmethod
    def _create_blank_audio_device() -> AudioDeviceDefinition:
        return AudioDeviceDefinition(
            sink          = "",
            source        = "",
            sink_volume   = -1.0,
            source_volume   = -1.0
        )

    def _get_audio_device(self, audio_type: str) -> AudioDeviceDefinition | None:
        device = self._create_blank_audio_device()

        if self._data is None:
            return device

        if audio_type not in self._data:
            return device

        return AudioDeviceDefinition(
            sink          = self._data[audio_type].get("sink", ""),
            source        = self._data[audio_type].get("source", ""),
            sink_volume   = float(self._data[audio_type].get("sink_volume", -1.0)),
            source_volume   = float(self._data[audio_type].get("source_volume", -1.0)),
        )

    def get_default_audio_device(self) -> AudioDeviceDefinition | None:
        return self._get_audio_device("default_audio_device")

    def get_radio_audio_device(self) -> AudioDeviceDefinition | None:
        return self._get_audio_device("radio_audio_device")

    def create_default_configuration(self):
        with open(self._filename, "w") as f:
            f.write("# autogenerated radio-interface-helper-ui config file @ {}\n".format(datetime.datetime.now()))
            f.write("#\n")
            f.write("# Found devices:\n")

            pwd = PipeWireDump()
            pwd.refresh()

            for node_name in pwd.get_node_names():
                node_id = pwd.get_node_id_by_name(node_name)
                f.write("# {}  ->  {}\n".format(node_id, node_name))

            f.write("\n")
            f.write("\n")

            f.write("[default_audio_device]\n")
            f.write("sink = \"\"\n")
            f.write("source = \"\"\n")
            f.write("sink_volume = -1.0  # -1.0 do not adjust audio when switching\n")
            f.write("source_volume = -1.0\n")
            f.write("\n")
            f.write("\n")

            f.write("[radio_audio_device]\n")
            f.write("sink = \"\"\n")
            f.write("source = \"\"\n")
            f.write("sink_volume = -1.0\n")
            f.write("source_volume = -1.0\n")